bar:
  datasource:
    url: jdbc:h2:mem:bar
    username: sa
    password: ''

foo:
  datasource:
    url: jdbc:h2:mem:foo
    username: sa
    password: ''

spring:
  output:
    ansi:
      enabled: ALWAYS
