
spring:
  datasource:
    url: jdbc:h2:mem:foo
    username: sa
    password: n/z7PyA5cvcXvs8px8FVmBVpaRyNsvJb3X7YfS38DJrIg25EbZaZGvH4aHcnc97Om0islpCAPc3MqsGvsrxVJw==

    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5
      filters: conn,config,stat,slf4j

      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true

      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 'x'

  output:
    ansi:
      enabled: ALWAYS

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALS8ng1XvgHrdOgm4pxrnUdt3sXtu/E8My9KzX8sXlz+mXRZQCop7NVQLne25pXHtZoDYuMh3bzoGj6v5HvvAQ8CAwEAAQ==