spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''

    hikari:
      minimumIdle: 5
      maximumPoolSize: 5
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000

  output:
    ansi:
      enabled: ALWAYS