spring:
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

    hikari:
      minimumIdle: 5
      maximumPoolSize: 5

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: ALWAYS